variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG
  DOCKER_PULL_SECRET: docker-registry-secret
  K8S_NAMESPACE_PREFIX: biosamples
  # take from variable or read from kubectl
  K8S_CLUSTER_URL: http://hx-rke-wp-webadmin-17-worker-1.caas.ebi.ac.uk
  APP_NAME: $CI_PROJECT_NAME

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - dist/

stages:
  - build
#  - publish
  - deploy

build_docker_image:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker --version
    - echo "CI_DEPLOY_USER $CI_DEPLOY_USER"
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_PASSWORD" "$CI_REGISTRY"
    - echo $DOCKER_IMAGE_NAME
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push --quiet $DOCKER_IMAGE_NAME
  after_script:
    - docker logout ${CI_REGISTRY}

deploy_dev:
  variables:
    ENVIRONMENT_NAME: dev
    HOST: wwwint.ebi.ac.uk
  environment:
    name: dev
    url: https://wwwint.ebi.ac.uk/biosamples/checklist-editor
  only:
    - dev
  extends: .kube_deploy_script

.kube_deploy_script:
  stage: deploy
  image: dtzar/helm-kubectl
  services:
    - docker:dind
  variables:
    K8S_NAMESPACE: ${K8S_NAMESPACE_PREFIX}-${ENVIRONMENT_NAME}
  script:
    - kubectl create namespace ${K8S_NAMESPACE} || true
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - kubectl create secret docker-registry $DOCKER_PULL_SECRET --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - helm upgrade checklist-editor ./chart --set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$DOCKER_TAG
    - kubectl rollout restart deployment ${APP_NAME}
    - echo ENVIRONMENT_NAME=${ENVIRONMENT_NAME} > .env
    - echo K8S_NAMESPACE=${K8S_NAMESPACE} > .env
  artifacts:
    paths:
      - .env

