variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG
  DOCKER_PULL_SECRET: docker-registry-secret

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - dist/

stages:
  - build
#  - publish
  - deploy

build_docker_image:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$CI_DEPLOY_USER" -p "$CI_DEPLOY_PASSWORD" "$CI_REGISTRY"
    - echo $DOCKER_IMAGE_NAME
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push --quiet $DOCKER_IMAGE_NAME
  after_script:
    - docker logout ${CI_REGISTRY}

deploy_dev:
  variables:
    NAMESPACE: biosamples-dev
  environment:
    name: dev
#    url: http://hx-rke-wp-webadmin-17-worker-1.caas.ebi.ac.uk:32655/biosamples/checklist-editor
  when: manual
  extends: .kube_deploy_script

deploy_test:
  variables:
    NAMESPACE: biosamples-test
  environment:
    name: prod
#    url: https://wwwdev.ebi.ac.uk/biosamples/checklist-editor
  when: manual
  extends: .kube_deploy_script

deploy_prod:
  variables:
    NAMESPACE: checklist-editor-prod
  environment:
    name: prod
#    url: https://www.ebi.ac.uk/biosamples/checklist-editor
  when: manual
  extends: .kube_deploy_script

.kube_deploy_script:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl create namespace $NAMESPACE || true
    - kubectl config set-context --current --namespace=${NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - kubectl create secret docker-registry $DOCKER_PULL_SECRET --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - envsubst < k8s/deployment.yaml > k8s/kubernetes.yaml
    - envsubst < k8s/ingress_template.yaml > k8s/ingress.yaml
    - kubectl apply -f k8s/
    - kubectl rollout restart deployments checklist-editor

