apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  HTTP_PROXY: "http://hx-wwwcache.ebi.ac.uk:3128"
  HTTPS_PROXY: "http://hx-wwwcache.ebi.ac.uk:3128"
  http_proxy: "http://hx-wwwcache.ebi.ac.uk:3128"
  https_proxy: "http://hx-wwwcache.ebi.ac.uk:3128"
  no_proxy: "localhost,.cluster.local"
  config.js: |
    window.__CONFIG__ = {
        SCHEMA_STORE_URL: "{{.Values.checklistEditor.baseUrl}}/api/v2",
        OLS_URL: "https://www.ebi.ac.uk/ols4/api",
        AUTH_API_URL: "{{.Values.checklistEditor.baseUrl}}/auth"
    };
  nginx.conf: |
    server {
      listen       80;
      server_name  localhost;

      access_log /var/log/nginx/access.log main;
      error_log /var/log/nginx/access.log debug;

      # redirect /api requests to the json-schema-store
      location {{.Values.checklistEditor.baseUrl}}/api {
          proxy_pass "{{ .Values.checklistEditor.schemaStoreUrl}}/api";
      }

      # redirect /auth requests to the webin
      location {{.Values.checklistEditor.baseUrl}}/auth {
          proxy_pass "{{ .Values.checklistEditor.webinUrl}}/auth";
      }

      location {{.Values.checklistEditor.baseUrl}} {
        alias   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ {{.Values.checklistEditor.baseUrl}}/index.html;
      }
      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }

    }
